src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descriptif;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif = true;

    /**
     * @ORM\ManyToOne(targetEntity=TypeEvenement::class, inversedBy="evenements")
     */
    private $type_evenement;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function __toString()
{
    return $this->titre;
}

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptif(): ?string
    {
        return $this->descriptif;
    }

    public function setDescriptif(?string $descriptif): self
    {
        $this->descriptif = $descriptif;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getTypeEvenement(): ?TypeEvenement
    {
        return $this->type_evenement;
    }

    public function setTypeEvenement(?TypeEvenement $type_evenement): self
    {
        $this->type_evenement = $type_evenement;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Alerte;
use App\Entity\Evenement;
use App\Entity\Image;
use App\Entity\PlatDuJour;
use Doctrine\ORM\Mapping\OrderBy;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AccueilController extends AbstractController
{
    /**
     * @Route("/", name="accueil")
     */
    public function accueil()
    {
        $platDuJour = $this->getDoctrine()->getRepository(PlatDuJour::class)->findBy([
            'actif' => 1
        ]);

        $alertes = $this->getDoctrine()->getRepository(Alerte::class)->findBy([
            'actif' => 1
        ]);

        $evenement = $this->getDoctrine()->getRepository(Evenement::class)->findByEvents();

        $image = $this->getDoctrine()->getRepository(Image::class)->findBy([
            'actif' => 1
        ]);

        return $this->render('accueil/accueil.html.twig', [
            'platDuJour' => $platDuJour,
            'alertes' => $alertes,
            'evenements' => $evenement,
            'images' => $image,
        ]);
    }

}

templates/accueil/accueil.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<!--ALERTE-->
{% for warning in alertes %}
<div class="alert alert-danger text-center" role="alert" style="background-color: rgba(255,0,23,0.76);padding-bottom: 12px;margin-bottom: 0px;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    <span style="color: #1c0003;">{{warning.alerte|raw}}</span>
</div>
{% endfor %}


<!--PLAT DU JOUR-->
<body id="background_img" style="font-family: Almarai, sans-serif;font-size: 14px;">
    <section class="d-flex float-none flex-column" id="accueil" style="height: 934px;">
        
        <div id="logo-ardoise" style="margin-top: 20px;">
            <div class="container" style="height: 380px;">
                <div class="row" style="padding: 20px;padding-right: 0;padding-left: 0;padding-top: 15px;height: 603px;">
                    <div class="col-lg-7 col-xl-8 offset-lg-0 offset-xl-0 d-flex flex-column justify-content-around" data-aos="fade-right" data-aos-duration="1000" data-aos-delay="1000">
                        <div id="img_echalote"></div>
                        <p id="p_accroche">“Mange de façon à manger ce que tu manges, et non pas de manière à être dévoré par ta nourriture.”<br></p>
                    </div>
                    <div class="col offset-lg-0 d-flex flex-column justify-content-between" data-aos="fade-left" data-aos-duration="1000" data-aos-delay="1000" data-aos-once="true" id="ardoise">
                        {% for plat in platDuJour %}
                            <p>{{plat.date|date("d/m/Y")}}</p>
                            <p>{{plat.plat|raw}}</p>
                        <a class="d-flex d-lg-flex flex-row justify-content-center align-self-center justify-content-xl-center" data-toggle="modal" data-bs-tooltip="" id="btn_reservation" href="#modal_reservation" style="margin-bottom: 10px;">RESERVATION</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div data-bs-parallax-bg="true" id="parallax" style="height: 450px;background: url('img/Bouchon.jpg') center / cover;background-color: #ffffff;"></div>

<!--EVENEMENT-->

    <div class="container" id="evenement">
        <div class="intro">
            <h2 class="text-center" id="heading" style="padding-bottom: 40px;padding-top: 20px;">Evenement à venir</h2>
            <div></div>
            {% for evenement in evenements %}
            <div class="card" data-aos="fade-up" data-aos-duration="600" data-aos-delay="100" id="card_evenement"  style="margin-bottom: 30px">
                <div class="card-body d-flex flex-column">
                    
                        <h4 class="d-xl-flex justify-content-xl-center card-title">{{ evenement.titre }}</h4>
                        <h6 class="text-muted d-xl-flex justify-content-xl-end card-subtitle mb-2">{{ evenement.date|date("d/m/Y") }}</h6>
                        <p class="card-text">{{ evenement.descriptif|raw }}</p>
                        <a class="card-link d-flex d-lg-flex flex-row justify-content-center align-self-end justify-content-xl-center" data-toggle="modal" data-bs-tooltip="" id="btn_reservation" href="#modal_reservation">RESERVATION</a>
                    
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

<!--CAROUSEL-->

<div class="container" style="padding-bottom: 50px;padding-top: 50px;">
    <div class="carousel slide" data-ride="carousel" data-aos="fade-down" data-aos-duration="600" data-aos-delay="300" id="carousel" >
        <div class="carousel-inner" role="listbox" data-aos="fade">
            {% for image in images %}
            <div class="carousel-item{% if loop.first %} active {% endif %}">
                <img class="rounded mx-auto d-block" src="{{ vich_uploader_asset(image, 'imageFile')}}" alt="Slide Image" style="height: 500px">
            </div>
            {% endfor %}
        </div>
        <div>
            <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>




<!--CONTACTL-->

    <div class="container">
        <h2 class="text-center" id="heading" style="padding-bottom: 30px;padding-top: 20px;">Où nous trouver</h2>
        <div class="row" style="margin-right: -15px;">
            <div class="col-md-5 col-lg-5 col-xl-5 offset-xl-0 d-flex flex-column justify-content-between" data-aos="fade" data-aos-duration="600" data-aos-delay="150" style="background-color: rgba(255,255,255,0.9);color: rgb(251,251,251);text-shadow: 1px 1px rgb(0,0,0);border-radius: 0px;height: 400px;padding-right: 15px;margin: 0px;margin-bottom: 15px;padding-top: 10px;padding-bottom: 15px;margin-right: 5px;margin-left: 5px;border: 0px solid rgb(145,119,37);">
                <p style="margin-bottom: 0px;">Adresse:&nbsp;<a href="https://www.google.fr/maps/place/L%E2%80%99%C3%89chalote/@45.7362847,4.8376243,17z/data=!3m1!4b1!4m5!3m4!1s0x47f4ea3b6a9a4bbd:0x1490907d23f0c2ed!8m2!3d45.736281!4d4.839813" style="text-shadow: 0px 0px;color: rgb(0,0,0);"
                        target="_blank"><br>93 Rue de Gerland, 69007 Lyon<br></a></p>
                <p style="margin-bottom: 0px;">Téléphone:&nbsp;<a href="tel:+33478726117" style="text-shadow: 0px 0px;color: rgb(0,0,0);"><br>04.78.72.61.17<br></a></p>
                <p style="margin-bottom: 0px;">Email:&nbsp;<a href="mailto:camillepierrick@lechalote.com" style="text-shadow: 0px 0px;color: rgb(0,0,0);" target="_blank"><br>camillepierrick@lechalote.com<br><br></a></p>
                <p style="margin-bottom: 0px;">Horaire:&nbsp;</p>
                <ul class="list-unstyled text-center" style="text-align: left;">
                    <li>Lundi 7h - 16h</li>
                    <li>Mardi 7h - 16h</li>
                    <li>Mercredi 7h - 20h</li>
                    <li>Jeudi 7h - 20h</li>
                    <li>Vendredi 7h - 20h</li>
                    <li>Samedi 7h - 16h</li>
                </ul>
                <p style="margin-bottom: 0px;text-align: center;color: #000000;text-shadow: 0px 0px;">Nous vous attendons, pensez à réserver</p>
            </div>
            <div class="col" data-aos="fade" data-aos-duration="600" data-aos-delay="150" id="plan_responsiv" style="padding-top: 0px;padding-left: 6px;padding-right: 6px;"><iframe allowfullscreen="" frameborder="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2784.7411989405646!2d4.837624315790387!3d45.73628472326746!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4ea3b6a9a4bbd%3A0x1490907d23f0c2ed!2zTOKAmcOJY2hhbG90ZQ!5e0!3m2!1sfr!2sfr!4v1593025262693!5m2!1sfr!2sfr"
                    width="100%" height="400" style="border-radius: 0px;border: 1px solid rgb(145,119,37) ;"></iframe>
            </div>
        </div>
    </div>
    <div class="d-flex d-xl-flex justify-content-center justify-content-xl-center" style="margin-top: 30px;margin-bottom: 30px;">
        <a class="d-flex d-lg-flex flex-row justify-content-center align-self-center justify-content-xl-center" data-toggle="modal" data-bs-tooltip="" id="btn_reservation" href="#modal_reservation">RESERVATION</a>
    </div>

{% endblock %}

templates/accueil/carte.html.twig
{% extends 'base.html.twig' %}


{% block body %}

<body id="background_img">
    <nav class="navbar navbar-light navbar-expand-md" style="background-color: rgba(51,51,51,0.63);">
        <h4 style="color: white;">Carte</h4>
        <div class="container-fluid"><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-repas"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon" style="border: 2px solid rgb(145,119,37);border-radius: 0px;width: 58px;height: 35px;padding: 0px;color: rgb(145,119,37);"></span></button>
            <div class="collapse navbar-collapse" id="navcol-repas">
                <ul class="nav navbar-nav">
                    {% for manger in mangers %}
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="#{{ manger.slug }}">{{ manger.categorie }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>

    <nav class="navbar navbar-light navbar-expand-md" style="background-color: rgba(51,51,51,0.63);">
        <h4 style="color: white;" class="text-center">Boissons</h4>
        <div class="container-fluid"><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-boisson"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon" style="border: 2px solid rgb(145,119,37);border-radius: 0px;width: 58px;height: 35px;padding: 0px;color: rgb(145,119,37);"></span></button>
            <div class="collapse navbar-collapse" id="navcol-boisson">
                <ul class="nav navbar-nav">
                    {% for boire in boires %}
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="#{{ boire.slug }}">{{ boire.categorie }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% for categorie in categories %}
            {% if categorie.aliments.id == 1 %}
                    <div id="panneau">
                    <h2 id="{{ categorie.slug}}" style="text-align: center;padding-top: 10px;padding-right: 0px;padding-bottom: 10px;color: rgb(145,119,37);text-shadow: 1px 1px 1px rgb(145,95,37);background-color: rgba(255,255,255,0.9);margin-bottom: 3px;margin-top: 5px;border-width: 2px;border-style: solid;">{{ categorie.categorie}}</h2>
                    {% for gulp in gulps %}
                        {% if gulp.carte.categorie == categorie.categorie %}
                        <div id="plat-body" style="margin-bottom: 1px;margin-top: 1px;">
                            <div class="d-flex flex-row justify-content-between flex-wrap" style="padding-right: 15px;padding-left: 15px;font-size: 14px;padding-top: 5px;">
                                <h5>{{ gulp.nom }}</h5>
                                <h5>{{ gulp.tarif }} €</h5>
                            </div>
                            <div>
                                <p style="padding-left: 15px;font-size: 12px;color: rgb(100,107,113);padding-bottom: 2px;margin-bottom: 0px;">{{ gulp.descriptif }}</p>
                            </div>
                        </div>
                        {% endif %}
                        
                    {% endfor %}
                </div>
            {% endif %}
                
            
        {% endfor %}

        {% for categorie in categories %}
            {% if categorie.aliments.id == 2 %}
                    <div id="panneau">
                    <h2 id="{{ categorie.slug}}" style="text-align: center;padding-top: 10px;padding-right: 0px;padding-bottom: 10px;color: rgb(145,119,37);text-shadow: 1px 1px 1px rgb(145,95,37);background-color: rgba(255,255,255,0.9);margin-bottom: 3px;margin-top: 5px;border-width: 2px;border-style: solid;">{{ categorie.categorie}}</h2>
                    {% for gulp in gulps %}
                        {% if gulp.carte.categorie == categorie.categorie %}
                        <div id="plat-body" style="margin-bottom: 1px;margin-top: 1px;">
                            <div class="d-flex flex-row justify-content-between flex-wrap" style="padding-right: 15px;padding-left: 15px;font-size: 14px;padding-top: 5px;">
                                <h5>{{ gulp.nom }}</h5>
                                <h5>{{ gulp.tarif }} €</h5>
                            </div>
                            <div>
                                <p style="padding-left: 15px;font-size: 12px;color: rgb(100,107,113);padding-bottom: 2px;margin-bottom: 0px;">{{ gulp.descriptif }}</p>
                            </div>
                        </div>
                        {% endif %}
                        
                    {% endfor %}
                </div>
            {% endif %}
                
            
        {% endfor %}
    </div>
    
    {% endblock %}

templates/accueil/contact.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<body id="background_img">
    
    <div class="container" style="color: rgb(145,119,37);">
            <h2 class="text-center" style="padding-bottom: 40px;padding-top: 20px;">Demande de devis personnalisé</h2>
            {{ form_start(contactForm) }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form_row(contactForm.nom) }}
                </div>
                <div class="form-group col-md-6">
                    {{ form_row(contactForm.email) }}
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    {{ form_row(contactForm.message) }}
                </div>
            </div>
            <div class="form-row">
                {{ form_row(contactForm.donne) }}
            </div>
            <button  type='submit' id='btn_reservation'><a>Envoyer votre demande</a></button>
            {{ form_end(contactForm) }}
    </div>

{% for message in app.flashes('message') %}
<div class="flash-notice">
    {{ message }}
</div>
{% endfor %}

<div class="container">
    <h2 class="text-center" id="heading" style="padding-bottom: 30px;padding-top: 20px;">Où nous trouver</h2>
    <div class="row" style="margin-right: -15px;">
        <div class="col-md-5 col-lg-5 col-xl-5 offset-xl-0 d-flex flex-column justify-content-between" data-aos="fade" data-aos-duration="600" data-aos-delay="150" style="background-color: rgba(255,255,255,0.9);color: rgb(251,251,251);text-shadow: 1px 1px rgb(0,0,0);border-radius: 0px;height: 400px;padding-right: 15px;margin: 0px;margin-bottom: 15px;padding-top: 10px;padding-bottom: 15px;margin-right: 5px;margin-left: 5px;border: 0px solid rgb(145,119,37);">
            <p style="margin-bottom: 0px;">Adresse:&nbsp;<a href="https://www.google.fr/maps/place/L%E2%80%99%C3%89chalote/@45.7362847,4.8376243,17z/data=!3m1!4b1!4m5!3m4!1s0x47f4ea3b6a9a4bbd:0x1490907d23f0c2ed!8m2!3d45.736281!4d4.839813" style="text-shadow: 0px 0px;color: rgb(0,0,0);"
                target="_blank"><br>93 Rue de Gerland, 69007 Lyon<br></a></p>
                <p style="margin-bottom: 0px;">Téléphone:&nbsp;<a href="tel:+33478726117" style="text-shadow: 0px 0px;color: rgb(0,0,0);"><br>04.78.72.61.17<br></a></p>
                <p style="margin-bottom: 0px;">Email:&nbsp;<a href="mailto:camillepierrick@lechalote.com" style="text-shadow: 0px 0px;color: rgb(0,0,0);" target="_blank"><br>camillepierrick@lechalote.com<br><br></a></p>
                <p style="margin-bottom: 0px;">Horaire:&nbsp;</p>
                <ul class="list-unstyled text-center" style="text-align: left;">
                    <li>Lundi 7h - 16h</li>
                    <li>Mardi 7h - 16h</li>
                    <li>Mercredi 7h - 20h</li>
                    <li>Jeudi 7h - 20h</li>
                    <li>Vendredi 7h - 20h</li>
                    <li>Samedi 7h - 16h</li>
                </ul>
                <p style="margin-bottom: 0px;text-align: center;color: #000000;text-shadow: 0px 0px;">Nous vous attendons, pensez à réserver</p>
            </div>
            <div class="col" data-aos="fade" data-aos-duration="600" data-aos-delay="150" id="plan_responsiv" style="padding-top: 0px;padding-left: 6px;padding-right: 6px;"><iframe allowfullscreen="" frameborder="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2784.7411989405646!2d4.837624315790387!3d45.73628472326746!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4ea3b6a9a4bbd%3A0x1490907d23f0c2ed!2zTOKAmcOJY2hhbG90ZQ!5e0!3m2!1sfr!2sfr!4v1593025262693!5m2!1sfr!2sfr"
                width="100%" height="400" style="border-radius: 0px;border: 1px solid rgb(145,119,37) ;"></iframe>
            </div>
        </div>
    </div>
    <div class="d-flex d-xl-flex justify-content-center justify-content-xl-center" style="margin-top: 30px;margin-bottom: 30px;">
        <a class="d-flex d-lg-flex flex-row justify-content-center align-self-center justify-content-xl-center" data-toggle="modal" data-bs-tooltip="" id="btn_reservation" href="#modal_reservation">RESERVATION</a>
    </div>
    
</body>
{% endblock %}

templates/accueil/devis.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="container" style="color: rgb(145,119,37);">
      <h2 class="text-center" style="padding-bottom: 40px;padding-top: 20px;">Demande de devis personnalisé</h2>
        {{ form_start(devisForm) }}
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form_row(devisForm.nom) }}
          </div>
          <div class="form-group col-md-6">
            {{ form_row(devisForm.email) }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form_row(devisForm.telephone) }}
          </div>
          <div class="form-group col-md-6">
            {{ form_row(devisForm.nombrePersonne) }}
          </div>
        </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              {{ form_row(devisForm.date) }}
            </div>
            <div class="form-group col-md-6">
              {{ form_row(devisForm.typeEvenement) }}
            </div>
          </div>
          <div class="form-row">
            <div class="col">
              {{ form_row(devisForm.message) }}
            </div>
          </div>
          <div class="form-row">
            {{ form_row(devisForm.donne) }}
          </div>
          <button  type='submit' id='btn_reservation'>Envoyer votre demande</button>
          {{ form_end(devisForm) }}
</div>

{% for message in app.flashes('message') %}
    <div class="flash-notice">
        {{ message }}
    </div>
{% endfor %}




<!--CAROUSEL-->
<body id="background_img">
    <div class="container" style="padding-bottom: 50px;padding-top: 50px;">
        <div class="carousel slide" data-ride="carousel" data-aos="fade-down" data-aos-duration="600" data-aos-delay="300" id="carousel" style="background-image: url(assets/img/building.jpg);background-position: center;background-size: cover;">
            <div class="carousel-inner" role="listbox" data-aos="fade">
                <div class="carousel-item active"><img class="w-100 d-block" src="img/black-and-white-bar-black-monochrome-monochrome-photography-64308-pxhere.com.jpg" alt="Slide Image"></div>
                <div class="carousel-item"><img class="w-100 d-block" src="img/cafe-coffee-aroma-food-produce-vegetable-654599-pxhere.com.jpg" alt="Slide Image"></div>
                <div class="carousel-item"><img class="w-100 d-block" src="img/bar-463476_1920.jpg" alt="Slide Image"></div>
            </div>
            <div><a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a><a class="carousel-control-next" href="#carousel" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a></div>
            <ol
                class="carousel-indicators">
                <li data-target="#carousel" data-slide-to="0" class="active"></li>
                <li data-target="#carousel" data-slide-to="1"></li>
                <li data-target="#carousel" data-slide-to="2"></li>
                </ol>
        </div>
</div>
</body>
{% endblock %}